### ISSUE TITLE
GUI is broken

### ISSUE THREAD

**Issue by unfa** [DISTRHO/MVerb#1]
Looks like some random X11 pixmap memory dumped into the window.

Probably related to:

https://github.com/DISTRHO/ProM/issues/1
https://github.com/x42/meters.lv2/issues/7

**Comment by falkTX** [comment]
screenshot please.

**Comment by unfa** [comment]
![mverb](https://cloud.githubusercontent.com/assets/491704/9022066/94cfe180-3865-11e5-88d5-5d57e3169f16.png)

Sorry, I forgot to attach it. I'm running it from Carla under KX Studio.

**Comment by simonvanderveldt** [comment]
I'm not seeing this with any of the plugin options or with the standalone binary (built from current master). Maybe a glitch in your video setup?

**Comment by falkTX** [comment]
I'm going to close this issue.
The bug is related to graphics drivers. This MVerb versions needs OpenGL2 in order to display the text (optional), but OpenGL1 is required as per all DPF based plugins.
